name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - rolling
        include:
          - ros_distribution: rolling
            docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    container:
      image: ${{ matrix.docker_image }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup workspace
        run: mkdir -p ros2_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ros2_shm_vision_demo
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
